#' Read in GDX and calculate electricity generation, used in convGDX2MIF.R for the reporting
#' 
#' Read in electricity generation data from GDX file, information used in convGDX2MIF.R
#' for the reporting
#' 
#' 
#' @param gdx a GDX object as created by readGDX, or the path to a gdx
#' @param output a magpie object containing all needed variables generated by other report*.R functions
#' @return MAgPIE object - contains the Generation variables
#' @author Sebastian Osorio, Renato Rodrigues
#' @seealso \code{\link{convGDX2MIF}}
#' @examples
#' 
#' \dontrun{reportGeneration(gdx)}
#'
#' @importFrom gdx readGDX
#' @importFrom magclass mbind setNames dimSums getSets getSets<- as.magpie
#' @export
#' 
reportGeneration <- function(gdx,output=NULL) {
  
  if(is.null(output)){
    stop("please provide a file containing all needed information")
  }
  
  # read sets
  t <- readGDX(gdx,name="t")
  tehe <- readGDX(gdx,name="tehe")
  teel <- readGDX(gdx,name="teel") #set of electricity generation technologies (non-storage)
  ter <- readGDX(gdx,name="ter") #set of variable renewable electricity generation technologies
  ternofluc <- readGDX(gdx,name="ternofluc") #set of non-variable (non-fluctuating) renewable electricity generation technologies
  tefossil <- readGDX(gdx,name="tefossil") #set of fossil-based electricity generation technologies
  tenr <- readGDX(gdx,name="tenr") #set of non-renewable electricity generation technologies (includes storage)
  tegas <- readGDX(gdx,name="tegas") #set of gas generation technologies
  telig <- readGDX(gdx,name="telig") #set of lignite generation technologies
  tecoal <- readGDX(gdx,name="tecoal") #set of hard coal generation technologies
  tengcc <- readGDX(gdx,name="tengcc") #set of NGCC generation technologies
  tehydro <- readGDX(gdx,name="tehydro") #set of hydropower generation technologies
  tehgen <- readGDX(gdx,name="tehgen")
  tehydro <- readGDX(gdx,name="tehydro")
  tebio <- readGDX(gdx,name="tebio")
  teoil <- readGDX(gdx,name="teoil")
  techp <- readGDX(gdx,name="techp")
  teccs <- readGDX(gdx,name="teccs")
  teothers <- readGDX(gdx,name="teothers")
  tau <- readGDX(gdx,name="tau") #set of time slices
  pety <- readGDX(gdx,name="pety") #set of primary energies
  tegas_el <- intersect(tegas,teel)
  tengcc_el <- intersect(tengcc,teel)
  testore <- readGDX(gdx,name="testore")
  pe2se <- readGDX(gdx,name="pe2se")
  pe2se <- paste0(pe2se[,1],".",pe2se[,2],".",pe2se[,3])
  
  # read parameters and sets
  p_taulength <- readGDX(gdx,name="p_taulength",field="l",format="first_found")[,,tau] #number of hours/year per tau
  p_tedata <- readGDX(gdx,name="p_tedata",field="l",format="first_found") #parameter per technology
  c_LIMESversion <- readGDX(gdx,name="c_LIMESversion",field="l",format="first_found")
  
  # read variables
  v_seprod <- readGDX(gdx,name="v_seprod",field="l",format="first_found",restore_zeros = FALSE)[,,tau]
  v_storeout <- readGDX(gdx,name="v_storeout",field="l",format="first_found")[,,tau]
  v_storein <- readGDX(gdx,name="v_storein",field="l",format="first_found")[,,tau]
  v_exdemand <- readGDX(gdx,name="v_exdemand",field="l",format="first_found",restore_zeros = FALSE)[,,tau] #demand
  
  #Make sure only the sets -> to reduce the size of the variables
  #v_seprod <- v_seprod[,,pe2se]
  v_seprod <- v_seprod[,,pety]
  p_autocons <- p_tedata[,,"autocons"]

  # create MagPie object of variables with iso3 regions
  v_seprod <- limesMapping(v_seprod)
  v_storeout <- limesMapping(v_storeout)
  v_storein <- limesMapping(v_storein)
  v_exdemand <- limesMapping(v_exdemand)
  p_autocons <- limesMapping(p_autocons)
  
  #Check the version so to choose the electricity-related variables
  if(c_LIMESversion >= 2.28) {
    
    v_seprod_el <- v_seprod[,,"seel"]
    c_heating <- readGDX(gdx,name="c_heating",field="l",format="first_found")
    
    if(c_heating == 1) {
      v_seprod_he <- v_seprod[,,"sehe"]
      v_seprod_he <- collapseNames(v_seprod_he)
      p_eldemand <- v_exdemand[,,"seel"]
      #v_seprod_el <- v_seprod[,,"seel"]
      
    } else {
      p_eldemand <- v_exdemand
      #v_seprod_el <- v_seprod
      v_storein_el <- v_storein
      v_storeout_el <- v_storeout
    }
    
  } else {
    p_eldemand <- v_exdemand
    v_seprod_el <- v_seprod
  }
  
  if(c_LIMESversion >= 2.37) { #First version with heat staorage
    v_storein_el <- v_storein[,,"seel"]
    v_storein_el <- v_storein_el[,,setdiff(testore,c("heat_sto"))]
    v_storeout_el <- v_storeout[,,"seel"]
    v_storeout_el <- v_storeout_el[,,setdiff(testore,c("heat_sto"))]
    v_storein_el <- collapseNames(v_storein_el)
    v_storeout_el <- collapseNames(v_storeout_el)
    
    v_storein_he <- v_storein[,,"sehe"]
    v_storein_he <- collapseNames(v_storein_he) #first collapse (to keep the technology name)
    v_storein_he <- v_storein_he[,,"heat_sto"] #then filter by technology
    v_storeout_he <- v_storeout[,,"sehe"]
    v_storeout_he <- collapseNames(v_storeout_he)
    v_storeout_he <- v_storeout_he[,,"heat_sto"]
  }
  
  #Collapse names to avoid some problems
  p_eldemand <- collapseNames(p_eldemand)
  v_seprod_el <- collapseNames(v_seprod_el)
  
  
  #generation per aggregated technology per country
  #and converting from GWh to TWh
  tmp1 <- NULL
  
  varList_el <- list(
    #Conventional
    "Secondary Energy|Electricity (TWh/yr)"                  =c(teel),
    "Secondary Energy|Electricity|Biomass (TWh/yr)"          =intersect(teel,tebio),
    "Secondary Energy|Electricity|Biomass|w/o CCS (TWh/yr)"  =intersect(teel,setdiff(tebio,teccs)),
    "Secondary Energy|Electricity|Coal (TWh/yr)"             =intersect(teel,c(tecoal,telig)),
    "Secondary Energy|Electricity|Coal|w/o CCS (TWh/yr)"     =intersect(teel,setdiff(c(tecoal,telig),teccs)),
    "Secondary Energy|Electricity|Coal|w/ CCS (TWh/yr)"      =intersect(teel,intersect(c(tecoal,telig),teccs)),
    "Secondary Energy|Electricity|Hard Coal (TWh/yr)"        =intersect(teel,c(tecoal)),
    "Secondary Energy|Electricity|Hard Coal|w/o CCS (TWh/yr)"=intersect(teel,setdiff(c(tecoal),teccs)),
    "Secondary Energy|Electricity|Hard Coal|w/ CCS (TWh/yr)" =intersect(teel,intersect(c(tecoal),teccs)),
    "Secondary Energy|Electricity|Lignite (TWh/yr)"          =intersect(teel,c(telig)),
    "Secondary Energy|Electricity|Lignite|w/o CCS (TWh/yr)"  =intersect(teel,setdiff(c(telig),teccs)),
    "Secondary Energy|Electricity|Lignite|w/ CCS (TWh/yr)"   =intersect(teel,intersect(c(telig),teccs)),
    "Secondary Energy|Electricity|Oil (TWh/yr)"              =intersect(teel,c(teoil)),
    "Secondary Energy|Electricity|Gas (TWh/yr)"              =intersect(teel,c(tegas)),
    "Secondary Energy|Electricity|Gas|w/o CCS (TWh/yr)"      =intersect(teel,setdiff(tegas_el,teccs)),
    "Secondary Energy|Electricity|Gas|w/ CCS (TWh/yr)"       =intersect(teel,intersect(tegas_el,teccs)),
    "Secondary Energy|Electricity|Gas CC|w/o CCS (TWh/yr)"   =intersect(teel,setdiff(tengcc_el,teccs)),
    "Secondary Energy|Electricity|Gas CC|w/ CCS (TWh/yr)"    =intersect(teel,intersect(tengcc_el,teccs)),
    "Secondary Energy|Electricity|Gas CC (TWh/yr)"           =intersect(teel,c(tengcc_el)),
    "Secondary Energy|Electricity|Gas OC (TWh/yr)"           =intersect(teel,setdiff(tegas_el,tengcc_el)),
    "Secondary Energy|Electricity|Other (TWh/yr)"            =intersect(teel,c(teothers)),
    "Secondary Energy|Electricity|Hydrogen (TWh/yr)"         =intersect(teel,c(tehgen)),
    "Secondary Energy|Electricity|Hydrogen FC (TWh/yr)"      =intersect(teel,c("hfc")),
    "Secondary Energy|Electricity|Hydrogen OC (TWh/yr)"      =intersect(teel,c("hct")),
    "Secondary Energy|Electricity|Hydrogen CC (TWh/yr)"      =intersect(teel,c("hcc")),
    "Secondary Energy|Electricity|Nuclear (TWh/yr)"          =intersect(teel,c("tnr")),
    "Secondary Energy|Electricity|Waste (TWh/yr)"            =intersect(teel,c("waste")),
    "Secondary Energy|Electricity|Other Fossil (TWh/yr)"     =intersect(teel,c(teothers,"waste",teoil)),
    
    #general aggregation
    "Secondary Energy|Electricity|Fossil (TWh/yr)"                 =intersect(teel,c(tefossil)),
    "Secondary Energy|Electricity|Fossil|w/o CCS (TWh/yr)"         =intersect(teel,setdiff(tefossil,teccs)),
    "Secondary Energy|Electricity|Fossil|w/ CCS (TWh/yr)"          =intersect(teel,intersect(tefossil,teccs)),
    "Secondary Energy|Electricity|Variable renewable (TWh/yr)"     =intersect(teel,c(ter)),
    "Secondary Energy|Electricity|Non-variable renewable (TWh/yr)" =intersect(teel,c(ternofluc)),
    "Secondary Energy|Electricity|Renewable (TWh/yr)"              =intersect(teel,c(ter,ternofluc)),
    "Secondary Energy|Electricity|Non-renewable (TWh/yr)"          =intersect(teel,tenr), #this does not include storage
    
    #Renewable
    "Secondary Energy|Electricity|Wind (TWh/yr)"         =intersect(teel,c("windon","windoff")),       
    "Secondary Energy|Electricity|Wind|Onshore (TWh/yr)" =intersect(teel,c("windon")),   
    "Secondary Energy|Electricity|Wind|Offshore (TWh/yr)"=intersect(teel,c("windoff")),      
    "Secondary Energy|Electricity|Solar (TWh/yr)"        =intersect(teel,c("spv","csp")),
    "Secondary Energy|Electricity|Solar|PV (TWh/yr)"     =intersect(teel,c("spv")), 
    "Secondary Energy|Electricity|Solar|CSP (TWh/yr)"    =intersect(teel,c("csp")),  
    "Secondary Energy|Electricity|Hydro (TWh/yr)"        =intersect(teel,c(tehydro))
  )
  
  for (var in names(varList_el)){
    tmp1 <- mbind(tmp1,setNames(dimSums(dimSums(v_seprod_el[,,varList_el[[var]]],dim=c(3.2,3.3))*p_taulength,dim=3)/1000,var))
  }
  
  #general aggregation
  tmp1 <- mbind(tmp1,setNames(dimSums((dimSums(v_seprod_el[,,c(teel)],dim=c(3.2,3.3)) + dimSums(v_storeout_el,dim=c(3.2)))*p_taulength,dim=3)/1000,"Secondary Energy|Electricity|w/ storage (TWh/yr)"))
  tmp1 <- mbind(tmp1,setNames(dimSums((dimSums(v_seprod_el[,,c(teel)],dim=c(3.2,3.3)) + dimSums(v_storeout_el,dim=c(3.2)) - dimSums(v_storein_el,dim=c(3.2)))*p_taulength,dim=3)/1000,"Secondary Energy||Electricity|w/o losses (TWh/yr)"))
  
  tmp2 <- NULL
  #when there is endogenous heating switch
  if(c_LIMESversion >= 2.33) {
    tewaste <- readGDX(gdx,name="tewaste") #set of waste generation technologies
    
    #Electricity (new technologies)
    tmp2 <- mbind(tmp2,setNames(dimSums(dimSums(v_seprod_el[,,intersect(tebio,teccs)],dim=c(3.2,3.3))*p_taulength,dim=3)/1000,"Secondary Energy|Electricity|Biomass|w/ CCS (TWh/yr)"))
    
    if(c_heating == 1) {
      #Additional sets needed
      teoel <- readGDX(gdx,name="teoel") #set of electricity-only generation technologies
      tedh <- readGDX(gdx,name="tedh") #set of District Heating generation technologies
      tedhelec <- readGDX(gdx,name="tedhelec") #set of electric District Heating generation technologies
      teheelec <- readGDX(gdx,name="teheelec") #set of electric-based Heating generation technologies
      teohecen <- readGDX(gdx,name="teohecen") #set of centralized heat-only generation technologies
      tehedec <- readGDX(gdx,name="tehedec") #set of decentralized heat generation technologies
      
      #1) HEAT FROM DH: CHP AND Heat-only 
      varList_he <- list(
        #1.b) CHP
        "Useful Energy|Heat|District Heating|CHP (TWh/yr)"                                         =c(techp),
        "Useful Energy|Heat|District Heating|CHP|Biomass (TWh/yr)"                                 =intersect(techp,tebio),
        "Useful Energy|Heat|District Heating|CHP|Coal (TWh/yr)"                                    =intersect(techp,c(tecoal,telig)),
        "Useful Energy|Heat|District Heating|CHP|Hard Coal (TWh/yr)"                               =intersect(techp,c(tecoal)),
        "Useful Energy|Heat|District Heating|CHP|Lignite (TWh/yr)"                                 =intersect(techp,c(telig)),
        "Useful Energy|Heat|District Heating|CHP|Oil (TWh/yr)"                                     =intersect(techp,c(teoil)),
        "Useful Energy|Heat|District Heating|CHP|Gas (TWh/yr)"                                     =intersect(techp,c(tegas)),
        "Useful Energy|Heat|District Heating|CHP|Gas CC (TWh/yr)"                                  =intersect(techp,c(tengcc_el)),
        "Useful Energy|Heat|District Heating|CHP|Gas OC (TWh/yr)"                                  =intersect(techp,setdiff(tegas_el,tengcc_el)),
        "Useful Energy|Heat|District Heating|CHP|Other (TWh/yr)"                                   =intersect(techp,c(teothers)),
        "Useful Energy|Heat|District Heating|CHP|Other Fossil (TWh/yr)"                            =intersect(techp,c(teothers,tewaste,teoil)),
        "Useful Energy|Heat|District Heating|CHP|Fossil (TWh/yr)"                                  =intersect(techp,c(tefossil)),
        "Useful Energy|Heat|District Heating|CHP|Renewable (TWh/yr)"                               =intersect(techp,c(ter,ternofluc)),
        "Useful Energy|Heat|District Heating|CHP|Non-renewable (TWh/yr)"                           =intersect(techp,tenr),
        
        #1.c) Only-heat (centralized boilers)
        "Useful Energy|Heat|District Heating|Heat-only (TWh/yr)"                                =c(teohecen),
        "Useful Energy|Heat|District Heating|Heat-only|Biomass (TWh/yr)"                        =intersect(teohecen,tebio),
        "Useful Energy|Heat|District Heating|Heat-only|Coal (TWh/yr)"                           =intersect(teohecen,c(tecoal,telig)),
        "Useful Energy|Heat|District Heating|Heat-only|Hard Coal (TWh/yr)"                      =intersect(teohecen,c(tecoal)),
        "Useful Energy|Heat|District Heating|Heat-only|Lignite (TWh/yr)"                        =intersect(teohecen,c(telig)),
        "Useful Energy|Heat|District Heating|Heat-only|Oil (TWh/yr)"                            =intersect(teohecen,c(teoil)),
        "Useful Energy|Heat|District Heating|Heat-only|Gas (TWh/yr)"                            =intersect(teohecen,c(tegas)),
        "Useful Energy|Heat|District Heating|Heat-only|Other (TWh/yr)"                          =intersect(teohecen,c(teothers)),
        "Useful Energy|Heat|District Heating|Heat-only|Waste (TWh/yr)"                          =intersect(teohecen,c(tewaste)),
        "Useful Energy|Heat|District Heating|Heat-only|Other Fossil (TWh/yr)"                   =intersect(teohecen,c(teothers,tewaste,teoil)),
        "Useful Energy|Heat|District Heating|Heat-only|Electricity (TWh/yr)"                    =intersect(teohecen,c(tedhelec)),
        "Useful Energy|Heat|District Heating|Heat-only|Electricity|Heat Pump (TWh/yr)"          =intersect(teohecen,"hp_large"),
        "Useful Energy|Heat|District Heating|Heat-only|Electricity|Electric Boiler (TWh/yr)"    =intersect(teohecen,"elboil_large"),
        "Useful Energy|Heat|District Heating|Heat-only|Solar (TWh/yr)"                          =intersect(teohecen,c("sol_heat")),
        "Useful Energy|Heat|District Heating|Heat-only|Geothermal (TWh/yr)"                     =intersect(teohecen,c("geo_heat")),
        "Useful Energy|Heat|District Heating|Heat-only|Fossil (TWh/yr)"                         =intersect(teohecen,c(tefossil)),
        "Useful Energy|Heat|District Heating|Heat-only|Renewable (TWh/yr)"                      =intersect(teohecen,c(ter,ternofluc)),
        "Useful Energy|Heat|District Heating|Heat-only|Non-renewable (TWh/yr)"                  =intersect(teohecen,tenr),
        
        #1.d) District Heating
        "Useful Energy|Heat|District Heating (TWh/yr)"                             =c(tedh),
        "Useful Energy|Heat|District Heating|Biomass (TWh/yr)"                     =intersect(tedh,tebio),
        "Useful Energy|Heat|District Heating|Coal (TWh/yr)"                        =intersect(tedh,c(tecoal,telig)),
        "Useful Energy|Heat|District Heating|Hard Coal (TWh/yr)"                   =intersect(tedh,c(tecoal)),
        "Useful Energy|Heat|District Heating|Lignite (TWh/yr)"                     =intersect(tedh,c(telig)),
        "Useful Energy|Heat|District Heating|Oil (TWh/yr)"                         =intersect(tedh,c(teoil)),
        "Useful Energy|Heat|District Heating|Gas (TWh/yr)"                         =intersect(tedh,c(tegas)),
        "Useful Energy|Heat|District Heating|Other (TWh/yr)"                       =intersect(tedh,c(teothers)),
        "Useful Energy|Heat|District Heating|Waste (TWh/yr)"                       =intersect(tedh,c(tewaste)),
        "Useful Energy|Heat|District Heating|Other Fossil (TWh/yr)"                =intersect(tedh,c(teothers,tewaste,teoil)),
        "Useful Energy|Heat|District Heating|Electricity (TWh/yr)"                 =intersect(tedh,c(tedhelec)),
        "Useful Energy|Heat|District Heating|Electricity|Heat Pump (TWh/yr)"       =intersect(tedh,"hp_large"),
        "Useful Energy|Heat|District Heating|Electricity|Electric Boiler (TWh/yr)" =intersect(tedh,"elboil_large"),
        "Useful Energy|Heat|District Heating|Solar (TWh/yr)"                       =intersect(tedh,c("sol_heat")),
        "Useful Energy|Heat|District Heating|Geothermal (TWh/yr)"                  =intersect(tedh,c("geo_heat")),
        "Useful Energy|Heat|District Heating|Fossil (TWh/yr)"                      =intersect(tedh,c(tefossil)),
        "Useful Energy|Heat|District Heating|Renewable (TWh/yr)"                   =intersect(tedh,c(ter,ternofluc)),
        "Useful Energy|Heat|District Heating|Non-renewable (TWh/yr)"               =intersect(tedh,tenr)
      )
      
      for (var in names(varList_he)){
        tmp2 <- mbind(tmp2,setNames(dimSums(dimSums(v_seprod_he[,,varList_he[[var]]],dim=c(3.2,3.3))*p_taulength,dim=3)/1000,var))
      }
      
      #EXPLANATION OF TERMINOLOGY (for DH):
      #Transformation input ----(etah)--->>>> transformation output -----(distribution losses)---->>> final energy|heat -------(ratio of energy service to energy consumption)------>>>> useful energy
      
      #1 (cont) Final energy (only for electricity-based heating)
      p_etah <- limesMapping(p_tedata[,,"etah"]) #this already includes distribution losses and ratio of energy service to energy consumption
      p_losses_DH <- readGDX(gdx,name="p_losses_DH",field="l",format="first_found") #DH distribution losses
      p_losses_DH <- limesMapping(p_losses_DH)
      p_bd_ratio_usefin <- readGDX(gdx,name="p_bd_ratio_usefin",field="l",format="first_found") #ratio of energy service to energy consumption
      p_bd_ratio_usefin <- limesMapping(p_bd_ratio_usefin)
      #Need to aggregate heat supply per year to be able to divide it by efficiency
      o_transfinput_he <- new.magpie(cells_and_regions = getRegions(v_seprod_he), years = getYears(v_seprod_he), names = tehe,
                                fill = NA, sort = FALSE, sets = NULL, unit = "unknown")
      o_transfoutput_he <- new.magpie(cells_and_regions = getRegions(v_seprod_he), years = getYears(v_seprod_he), names = tehe,
                                fill = NA, sort = FALSE, sets = NULL, unit = "unknown")
      o_finalenergy_he <- new.magpie(cells_and_regions = getRegions(v_seprod_he), years = getYears(v_seprod_he), names = tehe,
                                fill = NA, sort = FALSE, sets = NULL, unit = "unknown")
      #Allocate values to array
      for (te_name in c(tehe)) {
        o_transfinput_he[,,te_name] <- (dimSums(collapseNames(v_seprod_he[,,te_name])*p_taulength,dim=3)/1000)/collapseNames(p_etah[,,te_name]) #transformation input
        o_transfoutput_he[,,te_name] <- (dimSums(collapseNames(v_seprod_he[,,te_name])*p_taulength,dim=3)/1000)/(collapseNames(p_etah[,,te_name]/((1-p_losses_DH)*p_bd_ratio_usefin))) #transformation output
        o_finalenergy_he[,,te_name] <- (dimSums(collapseNames(v_seprod_he[,,te_name])*p_taulength,dim=3)/1000)/(collapseNames(p_etah[,,te_name]/p_bd_ratio_usefin)) #final energy|heat
      }
      
      #Transformation input  
      varList_he2 <- list(
        "Transformation input|Heat|District Heating (TWh/yr)"                             =c(tedh),
        "Transformation input|Heat|District Heating|CHP (TWh/yr)"                         =c(techp),
        "Transformation input|Heat|District Heating|Heat-only (TWh/yr)"                   =c(teohecen),
        "Transformation input|Heat|Electricity|District Heating (TWh/yr)"                 =intersect(tedh,c(tedhelec)),
        "Transformation input|Heat|Electricity|District Heating|Heat Pump (TWh/yr)"       =intersect(tedh,"hp_large"),
        "Transformation input|Heat|Electricity|District Heating|Electric Boiler (TWh/yr)" =intersect(tedh,"elboil_large")
      )
      for (var in names(varList_he2)){
        tmp2 <- mbind(tmp2,setNames(dimSums(o_transfinput_he[,,varList_he2[[var]]],dim=3),var))
      }
      
      #Transformation output  
      varList_he2 <- list(
        "Transformation output|Heat|District Heating (TWh/yr)"                             =c(tedh),
        "Transformation output|Heat|District Heating|CHP (TWh/yr)"                         =c(techp),
        "Transformation output|Heat|District Heating|Heat-only (TWh/yr)"                   =c(teohecen),
        "Transformation output|Heat|Electricity|District Heating (TWh/yr)"                 =intersect(tedh,c(tedhelec)),
        "Transformation output|Heat|Electricity|District Heating|Heat Pump (TWh/yr)"       =intersect(tedh,"hp_large"),
        "Transformation output|Heat|Electricity|District Heating|Electric Boiler (TWh/yr)" =intersect(tedh,"elboil_large")
      )
      for (var in names(varList_he2)){
        tmp2 <- mbind(tmp2,setNames(dimSums(o_transfoutput_he[,,varList_he2[[var]]],dim=3),var))
      }
      
      #Final energy
      varList_he2 <- list(
        #"Final Energy|Heat|District Heating (TWh/yr)"                             =c(tedh),
        #"Final Energy|Heat|District Heating|CHP (TWh/yr)"                         =c(techp),
        #"Final Energy|Heat|District Heating|Heat-only (TWh/yr)"                   =c(teohecen),
        "Final Energy|Electricity|District Heating|Heat (TWh/yr)"                 =intersect(tedh,c(tedhelec)),
        "Final Energy|Electricity|District Heating|Heat Pump|Heat (TWh/yr)"       =intersect(tedh,"hp_large"),
        "Final Energy|Electricity|District Heating|Electric Boiler|Heat (TWh/yr)" =intersect(tedh,"elboil_large")
      ) 
      for (var in names(varList_he2)){
        tmp2 <- mbind(tmp2,setNames(dimSums(o_finalenergy_he[,,varList_he2[[var]]],dim=3),var))
      }
      
      
      #1 (cont) Decentralized heat
      c_buildings <- readGDX(gdx,name="c_buildings",field="l",format="first_found") #switch on buildings module
      if(c_buildings == 1) {
        
        #Useful energy
        varList_he <- list(
          #1.a) ALL heat production
          "Useful Energy|Heat|Electricity (TWh/yr)"          =intersect(tehe,c(teheelec)),
          
          #1.d) Decentralized heating (only electricity-based)
          "Useful Energy|Heat|Electricity|Decentralized (TWh/yr)"                             =intersect(tehedec,teheelec),
          "Useful Energy|Heat|Electricity|Decentralized|Heat Pump (TWh/yr)"                   =intersect(tehedec,c("hp_sh_dec","hp_wh_dec")),
          "Useful Energy|Heat|Electricity|Decentralized|Resistive electric heater (TWh/yr)"   =intersect(tehedec,"resheat_dec"),
          "Useful Energy|Heat|Electricity|Decentralized|Conventional heater (TWh/yr)"         =intersect(tehedec,"convheat_dec"),
          "Useful Energy|Heat|Electricity|Decentralized|Conventional water heater (TWh/yr)"   =intersect(tehedec,"convwh_dec")
        )
        
        for (var in names(varList_he)){
          tmp2 <- mbind(tmp2,setNames(dimSums(dimSums(v_seprod_he[,,varList_he[[var]]],dim=c(3.2,3.3))*p_taulength,dim=3)/1000,var))
        }
        
        #Final energy
        varList_he2 <- list(
          "Final Energy|Electricity|Heat (TWh/yr)"                                           =intersect(tehe,c(teheelec)),
          "Final Energy|Electricity|Decentralized|Heat (TWh/yr)"                             =intersect(tehedec,teheelec),
          "Final Energy|Electricity|Decentralized|Heat Pump|Heat (TWh/yr)"                   =intersect(tehedec,c("hp_sh_dec","hp_wh_dec")),
          "Final Energy|Electricity|Decentralized|Resistive electric heater|Heat (TWh/yr)"   =intersect(tehedec,"resheat_dec"),
          "Final Energy|Electricity|Decentralized|Conventional heater|Heat (TWh/yr)"         =intersect(tehedec,"convheat_dec"),
          "Final Energy|Electricity|Decentralized|Conventional water heater|Heat (TWh/yr)"   =intersect(tehedec,"convwh_dec")
        )
        
        for (var in names(varList_he2)){
          tmp2 <- mbind(tmp2,setNames(dimSums(o_finalenergy_he[,,varList_he2[[var]]],dim=3),var))
        }
        
      }
      
      #2. ELECTRICITY FROM CHP AND ELECTRICITY-ONLY PLANTS
      varList_el2 <- list(
        #2.a) CHP
        "Secondary Energy|Electricity|CHP (TWh/yr)"               =c(techp),
        "Secondary Energy|Electricity|CHP|Biomass (TWh/yr)"       =intersect(techp,tebio),
        "Secondary Energy|Electricity|CHP|Coal (TWh/yr)"          =intersect(techp,c(tecoal,telig)),
        "Secondary Energy|Electricity|CHP|Hard Coal (TWh/yr)"     =intersect(techp,c(tecoal)),
        "Secondary Energy|Electricity|CHP|Lignite (TWh/yr)"       =intersect(techp,c(telig)),
        "Secondary Energy|Electricity|CHP|Oil (TWh/yr)"           =intersect(techp,c(teoil)),
        "Secondary Energy|Electricity|CHP|Gas (TWh/yr)"           =intersect(techp,c(tegas)),
        "Secondary Energy|Electricity|CHP|Gas CC (TWh/yr)"        =intersect(techp,c(tengcc_el)),
        "Secondary Energy|Electricity|CHP|Gas OC (TWh/yr)"        =intersect(techp,setdiff(tegas_el,tengcc_el)),
        "Secondary Energy|Electricity|CHP|Other (TWh/yr)"         =intersect(techp,c(teothers)),
        "Secondary Energy|Electricity|CHP|Other Fossil (TWh/yr)"  =intersect(techp,c(teothers,tewaste,teoil)),
        "Secondary Energy|Electricity|CHP|Fossil (TWh/yr)"        =intersect(techp,c(tefossil)),
        "Secondary Energy|Electricity|CHP|Renewable (TWh/yr)"     =intersect(techp,c(ter,ternofluc)),
        "Secondary Energy|Electricity|CHP|Non-renewable (TWh/yr)" =intersect(techp,tenr),
        
        #2.b) Electricity-only
        "Secondary Energy|Electricity|Electricity-only (TWh/yr)"                  =c(teoel),
        "Secondary Energy|Electricity|Electricity-only|Biomass (TWh/yr)"          =intersect(teoel,tebio),
        "Secondary Energy|Electricity|Electricity-only|Biomass|w/o CCS (TWh/yr)"  =intersect(teoel,setdiff(tebio,teccs)),
        "Secondary Energy|Electricity|Electricity-only|Coal (TWh/yr)"             =intersect(teoel,c(tecoal,telig)),
        "Secondary Energy|Electricity|Electricity-only|Coal|w/o CCS (TWh/yr)"     =intersect(teoel,setdiff(c(tecoal,telig),teccs)),
        "Secondary Energy|Electricity|Electricity-only|Coal|w/ CCS (TWh/yr)"      =intersect(teoel,intersect(c(tecoal,telig),teccs)),
        "Secondary Energy|Electricity|Electricity-only|Hard Coal (TWh/yr)"        =intersect(teoel,c(tecoal)),
        "Secondary Energy|Electricity|Electricity-only|Hard Coal|w/o CCS (TWh/yr)"=intersect(teoel,setdiff(c(tecoal),teccs)),
        "Secondary Energy|Electricity|Electricity-only|Hard Coal|w/ CCS (TWh/yr)" =intersect(teoel,intersect(c(tecoal),teccs)),
        "Secondary Energy|Electricity|Electricity-only|Lignite (TWh/yr)"          =intersect(teoel,c(telig)),
        "Secondary Energy|Electricity|Electricity-only|Lignite|w/o CCS (TWh/yr)"  =intersect(teoel,setdiff(c(telig),teccs)),
        "Secondary Energy|Electricity|Electricity-only|Lignite|w/ CCS (TWh/yr)"   =intersect(teoel,intersect(c(telig),teccs)),
        "Secondary Energy|Electricity|Electricity-only|Oil (TWh/yr)"              =intersect(teoel,c(teoil)),
        "Secondary Energy|Electricity|Electricity-only|Gas (TWh/yr)"              =intersect(teoel,c(tegas)),
        "Secondary Energy|Electricity|Electricity-only|Gas|w/o CCS (TWh/yr)"      =intersect(teoel,setdiff(tegas_el,teccs)),
        "Secondary Energy|Electricity|Electricity-only|Gas|w/ CCS (TWh/yr)"       =intersect(teoel,intersect(tegas_el,teccs)),
        "Secondary Energy|Electricity|Electricity-only|Gas CC (TWh/yr)"           =intersect(teoel,c(tengcc_el)),
        "Secondary Energy|Electricity|Electricity-only|Gas OC (TWh/yr)"           =intersect(teoel,setdiff(tegas_el,tengcc_el)),
        "Secondary Energy|Electricity|Electricity-only|Other (TWh/yr)"            =intersect(teoel,c(teothers)),
        "Secondary Energy|Electricity|Electricity-only|Hydrogen (TWh/yr)"         =intersect(teoel,c(tehgen)),
        "Secondary Energy|Electricity|Electricity-only|Waste (TWh/yr)"            =intersect(teoel,c("waste")),
        "Secondary Energy|Electricity|Electricity-only|Other Fossil (TWh/yr)"     =intersect(teoel,c(teothers,"waste",teoil)),
        "Secondary Energy|Electricity|Electricity-only|Fossil (TWh/yr)"           =intersect(teoel,c(tefossil)),
        "Secondary Energy|Electricity|Electricity-only|Fossil|w/o CCS (TWh/yr)"   =intersect(teoel,setdiff(tefossil,teccs)),
        "Secondary Energy|Electricity|Electricity-only|Fossil|w/ CCS (TWh/yr)"    =intersect(teoel,intersect(tefossil,teccs)),
        "Secondary Energy|Electricity|Electricity-only|Renewable (TWh/yr)"        =intersect(teoel,c(ter,ternofluc)),
        "Secondary Energy|Electricity|Electricity-only|Non-renewable (TWh/yr)"    =intersect(teoel,tenr) #this does not include storage
      )
      
      for (var in names(varList_el2)){
        tmp2 <- mbind(tmp2,setNames(dimSums(dimSums(v_seprod_el[,,varList_el2[[var]]],dim=c(3.2,3.3))*p_taulength,dim=3)/1000,var))
      }
      
    }
    
  }
  
  # add global values
  tmp3 <- mbind(tmp1,tmp2)
  
  
  #STORAGE-RELATED
  tmp4 <- NULL
  
  #Storage generation
  varList_st <- list(
    "Secondary Energy|Electricity|Storage (TWh/yr)"                       =setdiff(testore,c("heat_sto")),
    "Secondary Energy|Electricity|Storage|Pump Hydro (TWh/yr)"            ="psp",           
    "Secondary Energy|Electricity|Storage|Stat Batteries (TWh/yr)"        ="batteries",               
    "Secondary Energy|Electricity|Storage|Hydrogen electrolysis (TWh/yr)" ="helec"
  )
  
  for (var in names(varList_st)){
    tmp4 <- mbind(tmp4,setNames(dimSums(dimSums(v_storeout_el[,,varList_st[[var]]],dim=c(3.2))*p_taulength,dim=3)/1000,var))
  }
  
  #Storage consumption
  varList_st <- list(
    "Secondary Energy|Electricity|Storage Consumption (TWh/yr)"                       =setdiff(testore,c("heat_sto")),
    "Secondary Energy|Electricity|Storage Consumption|Pump Hydro (TWh/yr)"            ="psp",           
    "Secondary Energy|Electricity|Storage Consumption|Stat Batteries (TWh/yr)"        ="batteries",               
    "Secondary Energy|Electricity|Storage Consumption|Hydrogen electrolysis (TWh/yr)" ="helec", 
    "Primary Energy|Electricity|Hydrogen (TWh/yr)"                                    ="helec"
  )
  
  for (var in names(varList_st)){
    tmp4 <- mbind(tmp4,setNames(dimSums(dimSums(v_storein_el[,,varList_st[[var]]],dim=c(3.2))*p_taulength,dim=3)/1000,var))
  }
  
  #Storage losses
  tmp4 <- mbind(tmp4,setNames(dimSums((dimSums(v_storein_el,dim=c(3.2)) - dimSums(v_storeout_el,dim=c(3.2)))*p_taulength/1000,dim=3),"Secondary Energy|Electricity|Storage Losses (TWh/yr)"))
  
  #Heat storage
  if(c_heating == 1) {
    tmp4 <- mbind(tmp4,setNames(dimSums(dimSums(v_storeout_he[,,],dim=c(3.2))*p_taulength,dim=3)/1000,"Useful Energy|Heat|Storage (TWh/yr)"))
    tmp4 <- mbind(tmp4,setNames(dimSums(dimSums(v_storein_he[,,],dim=c(3.2))*p_taulength,dim=3)/1000,"Useful Energy|Heat|Storage Consumption (TWh/yr)"))
    tmp4 <- mbind(tmp4,setNames(dimSums((dimSums(v_storein_he,dim=c(3.2)) - dimSums(v_storeout_he,dim=c(3.2)))*p_taulength/1000,dim=3),"Useful Energy|Heat|Storage Losses (TWh/yr)"))
  }
  
  
  #Hydrogen (from electrolysis) used in hydrogen-based generation plants
  if(c_LIMESversion >= 2.36) {
    #t <- readGDX(gdx,name="t",field="l",format="first_found") #time set
    t0 <- readGDX(gdx,name="t0",field="l",format="first_found") #initial year
    c_esmdisrate <- readGDX(gdx,name="c_esmdisrate",field="l",format="first_found") #interest rate
    p_ts <- readGDX(gdx,name="p_ts",field="l",format="first_found") #time-step
    
    v_p2xse <- readGDX(gdx,name="v_p2xse",field="l",format="first_found")[,,"pehgen.seel"] #[GWh]
    v_p2xse <- v_p2xse[,,tehgen]
    v_p2xse <- limesMapping(v_p2xse[,,tau])
    m_p2x <- readGDX(gdx,name="q_p2x",field="m",format="first_found") #[Geur/GWh]
    m_p2x <- limesMapping(m_p2x[,,tau])
    m_p2x <- m_p2x/p_taulength
    v_otherse <- readGDX(gdx,name="v_otherse",field="l",format="first_found")[,,"pehgen"] #[GWh]
    v_otherse <- limesMapping(v_otherse[,,tau])
    
    #Aggregate hydrogen used by different generation technologies, i.e., hydrogen used to produce electricity
    o_p2xse <- dimSums(v_p2xse[,,tehgen],dim=c(3.2))
    
    o_p2x <- new.magpie(cells_and_regions = getRegions(m_p2x), years = getYears(m_p2x), names = tau,
                                   fill = NA, sort = FALSE, sets = NULL, unit = "unknown")
    
    #Adjust v_p2xse
    #There are few cases where v_p2xse is higher than v_seprod (wasting electricity in hydrogen, instead of curtailing)
    o_seprod_hgen <- collapseNames(v_seprod_el[,,"pehgen"])
    #v_p2xse <- pmin(v_p2xse,o_seprod_hgen, na.rm = TRUE)
    
    for (t2 in getYears(m_p2x)) {
      o_p2x[,t2,] <- m_p2x[,t2,]
    }
    
    #compute factor to discount average marginal values
    f_npv <- as.numeric(p_ts)*exp(-as.numeric(c_esmdisrate)*(as.numeric(t)-as.numeric(t0)))
    
    o_p2x_disc <- NULL
    
    for (t2 in 1:length(t)) {
      o_p2x_disc <- mbind(o_p2x_disc,-o_p2x[,t2,]/as.numeric(f_npv[t2])) #[Geur 2010/GWh]
    }
    o_p2x_disc <- pmax(o_p2x_disc,0)
    
    tmp4 <- mbind(tmp4,setNames(1e6*dimSums(o_p2x_disc*p_taulength*o_p2xse,dim=3)/
                                  dimSums(p_taulength*o_p2xse,3),"Price|Primary Energy|Hydrogen [electrolysis] (Eur2010/MWh)"))
    
    varList_hgen <- list(
      "Primary Energy|Hydrogen [electrolysis]|Electricity (TWh/yr)"               = NA,
      "Primary Energy|Hydrogen [electrolysis]|Electricity|Hydrogen FC (TWh/yr)" = "hfc",
      "Primary Energy|Hydrogen [electrolysis]|Electricity|Hydrogen OC (TWh/yr)" = "hct",
      "Primary Energy|Hydrogen [electrolysis]|Electricity|Hydrogen CC (TWh/yr)" = "hcc"
    )
    
    for (var in names(varList_hgen)){
      tmp4 <- mbind(tmp4,setNames(dimSums(dimSums(v_p2xse[,,varList_hgen[[var]]],dim=c(3.2))*p_taulength,dim=3)/1000,var))
    }
    
    #Hydrogen from external sources
    o_hgen_ext <- setNames(output[,,"Primary Energy|Hydrogen|Electricity (TWh/yr)"],NULL)-setNames(tmp4[,,"Primary Energy|Hydrogen [electrolysis]|Electricity (TWh/yr)"],NULL)
    tmp4 <- mbind(tmp4,setNames(o_hgen_ext,"Primary Energy|Hydrogen [external]|Electricity (TWh/yr)"))
    
    #Weighted price for hydrogen
    o_pricehgen_weighted <- (setNames(output[,,"Price|Primary Energy|Hydrogen [external] (Eur2010/GJ)"],NULL)*setNames(tmp4[,,"Primary Energy|Hydrogen [external]|Electricity (TWh/yr)"],NULL)*3.6 + #Eur/GJ to eur/MWh
                               setNames(tmp4[,,"Price|Primary Energy|Hydrogen [electrolysis] (Eur2010/MWh)"],NULL)*setNames(tmp4[,,"Primary Energy|Hydrogen [electrolysis]|Electricity (TWh/yr)"],NULL))/
      (setNames(tmp4[,,"Primary Energy|Hydrogen [external]|Electricity (TWh/yr)"],NULL) + setNames(tmp4[,,"Primary Energy|Hydrogen [electrolysis]|Electricity (TWh/yr)"],NULL))
    tmp4 <- mbind(tmp4,setNames(o_pricehgen_weighted,"Price|Primary Energy|Hydrogen (Eur2010/MWh)"))
    
    #Hydrogen produced from electricity (electrolysis input - losses)
    p_eta <- p_tedata[,,"eta"]
    p_eta_helec <- limesMapping(p_eta)[,,"helec"]
    tmp4 <- mbind(tmp4,setNames(p_eta_helec*setNames(tmp4[,,"Primary Energy|Electricity|Hydrogen (TWh/yr)"],NULL),"Secondary Energy|Hydrogen|Electricity (TWh/yr)"))
    
    if(c_LIMESversion >= 2.36) {
      tau2season <- readGDX(gdx,name="tau2season") #mapping of tau's belonging to each season
      
      seasons <- c("winter","spring","summer","autumn")
      for(i in 1:length(seasons)) {
        taus <- c(tau2season$tau[tau2season$season == seasons[i]])
        if(length(taus) == 0) {
          o_outputhelec <- new.magpie(cells_and_regions = getRegions(o_p2xse), years = getYears(o_p2xse), names = paste0("Primary Energy|Hydrogen [electrolysis]|Electricity|",seasons[i]," (TWh/yr)"),
                                     fill = 0, sort = FALSE, sets = NULL, unit = "unknown")
          o_inputhelec <- new.magpie(cells_and_regions = getRegions(o_p2xse), years = getYears(o_p2xse), names = paste0("Primary Energy|Electricity|Hydrogen|",seasons[i]," (TWh/yr)"),
                                      fill = 0, sort = FALSE, sets = NULL, unit = "unknown")
          tmp4 <- mbind(tmp4,o_outputhelec)
          tmp4 <- mbind(tmp4,o_inputhelec)
        } else {
          tmp4 <- mbind(tmp4,setNames(dimSums(o_p2xse[,,taus]*p_taulength[,,taus],dim=3)/1000,paste0("Primary Energy|Hydrogen [electrolysis]|Electricity|",seasons[i]," (TWh/yr)")))
          o_inputhelec <- v_storein_el[,,"helec"]
          tmp4 <- mbind(tmp4,setNames(dimSums(dimSums(o_inputhelec[,,taus],dim=c(3.2))*p_taulength[,,taus],dim=3)/1000,paste0("Primary Energy|Electricity|Hydrogen|",seasons[i]," (TWh/yr)")))
        }
        
      }
    }
  }
  
  #aggregate tmp
  tmp5 <- mbind(tmp3,tmp4)
  
  #Gross production and demand
  tmp6 <- NULL
  #Need to create a variable with t,regi,te for gross production (v_seprod has these indexes)
  o_grossprod <- new.magpie(cells_and_regions = getRegions(v_seprod_el), years = getYears(v_seprod_el), names = c(teel),
                                       fill = 0, sort = FALSE, sets = NULL, unit = "unknown")
  #Estimate annual gross production for different technologies (in TWh/yr)
  for (teel2 in teel) {
    o_grossprod[,,teel2] <- dimSums(collapseNames(dimSums(v_seprod_el[,,teel2],dim=c(3.2)))*p_taulength/1000,dim=3)*(1+p_autocons[,,teel2])
  }
  
  tmp6 <- mbind(tmp6,setNames(dimSums(o_grossprod[,,intersect(teel,c(telig))],dim=3),"Gross Production|Electricity|Lignite (TWh/yr)"))
  tmp6 <- mbind(tmp6,setNames(dimSums(o_grossprod[,,intersect(teel,c(tecoal))],dim=3),"Gross Production|Electricity|Coal (TWh/yr)"))
  tmp6 <- mbind(tmp6,setNames(dimSums(o_grossprod[,,intersect(teel,c(tegas))],dim=3),"Gross Production|Electricity|Gas (TWh/yr)"))
  tmp6 <- mbind(tmp6,setNames(dimSums(o_grossprod[,,intersect(teel,c(tefossil))],dim=3),"Gross Production|Electricity|Fossil (TWh/yr)"))
  tmp6 <- mbind(tmp6,setNames(dimSums(o_grossprod[,,intersect(teel,c("tnr"))],dim=3),"Gross Production|Electricity|Nuclear (TWh/yr)"))
  
  #Net imports
  o_netimpots <- new.magpie(cells_and_regions = getRegions(p_eldemand), years = getYears(p_eldemand), names = tau,
                                         fill = 0, sort = FALSE, sets = NULL, unit = "unknown")
  o_netimpots <- dimSums(p_eldemand*p_taulength/1000,dim=3) - setNames(tmp1[,,"Secondary Energy||Electricity|w/o losses (TWh/yr)"],NULL)
  
  #Gross demand (gross electricity production + net imports), following official german statistics procedure
  o_grossdem <- dimSums(o_grossprod,dim=c(3.1)) + o_netimpots
  tmp6 <- mbind(tmp6,setNames(o_grossdem,"Secondary Energy|Electricity|Gross Demand (TWh/yr)"))
  tmp6 <- mbind(tmp6,setNames(dimSums(o_grossprod[,,intersect(teel,c(ter,ternofluc))],dim=3)/o_grossdem,"Secondary Energy|Electricity|Share of renewables in gross demand (--)"))
  
  #merge tmp's
  tmp7 <- mbind(tmp5,tmp6)
  
  #CURTAILMENT
  v_seprodmax <- readGDX(gdx,name="v_seprodmax",field="l",format="first_found",restore_zeros = FALSE)[,,tau]
  v_seprodmax <- limesMapping(v_seprodmax)
  o_genvres <- setNames(tmp1[,,"Secondary Energy|Electricity|Variable renewable (TWh/yr)"],NULL) 
  tmp8 <- NULL
  tmp8 <- mbind(tmp8,setNames(dimSums(dimSums(v_seprodmax[,,ter],dim=c(3.2))*p_taulength,dim=3)/1000-o_genvres,"Secondary Energy|Electricity|Curtailment (TWh/yr)"))
  
  #merge tmp's
  tmp <- mbind(tmp7,tmp8)

  return(tmp)
}