#' Read in GDX and calculate the load factor, used in convGDX2MIF.R for the reporting
#' 
#' Read in electricity generation data from GDX file, information used in convGDX2MIF.R
#' for the reporting
#' 
#' 
#' @param gdx a GDX object as created by readGDX, or the path to a gdx
#' @param output a magpie object containing all needed variables generated by other report*.R functions
#' @return MAgPIE object - contains the capacity variables
#' @author Sebastian Osorio
#' @seealso \code{\link{convGDX2MIF}}
#' @examples
#' 
#' \dontrun{reportLoadFactor(gdx)}
#'
#' @importFrom gdx readGDX
#' @importFrom magclass mbind setNames dimSums getSets getSets<- as.magpie 
#' @export
#' 
reportLoadFactor <- function(gdx,output=NULL) {
 
  if(is.null(output)){
    stop("please provide a file containing all needed information")
  }
  
  #Names of variables in output
  names_output <- getNames(output)
  
  #Find the positions where generation and capacities are
  pos_gen <- grep("Secondary Energy[|]Electricity[|]",names_output)
  pos_cap <- grep("Capacity[|]Electricity[|]",names_output)
  
  #Technologies for which generation and capacity are calculated
  var_gen_tmp <- gsub("Secondary Energy[|]Electricity[|]","",names_output[pos_gen])
  var_gen_tmp <- gsub(" [(]TWh/yr[)]","",gsub(" [(]--[)]","",var_gen_tmp))
  unit_gen_tmp <- sapply(strsplit(names_output[pos_gen]," [(]"),function(x) x[2]) #strsplit splits the vector with var names (in form of list) and sapply allows accessing all the second elements in the list
  unit_gen_tmp <- paste0("(",unit_gen_tmp)
  
  var_cap_tmp <- gsub("Capacity[|]Electricity[|]","",names_output[pos_cap])
  var_cap_tmp <- gsub(" [(]GWh[)]","",gsub(" [(]GW[)]","",var_cap_tmp))
  unit_cap_tmp <- sapply(strsplit(names_output[pos_cap]," [(]"),function(x) x[2]) #strsplit splits the vector with var names (in form of list) and sapply allows accessing all the second elements in the list
  unit_cap_tmp <- paste0("(",unit_cap_tmp)
  
  #find which variables match
  tech_match <- intersect(var_gen_tmp,var_cap_tmp)
  
  #Rebuild the variable names (w/ units) - the cleanest way would be using the units extracted above
  var_gen <- paste0("Secondary Energy|Electricity|",tech_match," (TWh/yr)")
  var_cap <- paste0("Capacity|Electricity|",tech_match," (GW)")
  
  #Calculate the load factor (need to convert units)
  o_loadfactor <- setNames(output[,,var_gen],tech_match)/(8760*setNames(output[,,var_cap],tech_match)/1000) #estimate factor ensuring gen and cap have the same names
  o_loadfactor <- setNames(o_loadfactor,paste0("Load Factor|Electricity|",tech_match," (--)"))
  tmp <- o_loadfactor
  
  return(tmp)
}
  
