#' Read in GDX and calculate emissions, used in convGDX2MIF.R for the reporting
#' 
#' Read in emissions data from GDX file, information used in convGDX2MIF.R
#' for the reporting
#' 
#' 
#' @param gdx a GDX object as created by readGDX, or the path to a gdx
#' @param output a magpie object containing all needed variables generated by other report*.R functions
#' @return MAgPIE object - contains the emission variables
#' @author Sebastian Osorio, Renato Rodrigues
#' @seealso \code{\link{convGDX2MIF}}
#' @examples
#' 
#' \dontrun{reportEmissions(gdx)}
#'
#' @importFrom gdx readGDX
#' @importFrom magclass mbind setNames dimSums getSets getSets<- as.magpie getItems
#' @export
#' 
reportFictitiousVars <- function(gdx,output=NULL) {
  
  if(is.null(output)){
    stop("please provide a file containing all needed information")
  }
  
  # read sets and parameters
  #tt <- readGDX(gdx,name="t")
  c_LIMESversion <- readGDX(gdx,name="c_LIMESversion",field="l",format="first_found")
  
  o_fictitious <- new.magpie(cells_and_regions = getItems(output, dim = 1), years = getYears(output), names = NULL,
                             fill = 0, sort = FALSE, sets = NULL, unit = "unknown")
  
  tmp1 <- NULL
  
  AggVarPath <- system.file("extdata","AggregateVariables.csv",package="limes")
  # reading mapping file
  AggVarfile <- read.csv(AggVarPath,sep=";")
  #  write the *.mif or give back the magpie opject output
  AggVars <- paste0(as.vector(AggVarfile$LIMES)," (",as.vector(AggVarfile$UnitLIMES) , ")")
  
  #Check the version: When there is endogenous heating, related emissions should not appear here (to avoid duplicates)
  if(c_LIMESversion >= 2.28) {
   heating <- .readHeatingCfg(gdx)
    if(heating == "fullDH") {
      AggVars <- AggVars[is.na(match(AggVars,"Emissions|CO2|Energy|Supply|Heat|District Heating (Mt CO2/yr)"))]
    }
  } 
  
  for (name_var in AggVars) {
    tmp1 <- mbind(tmp1,setNames(o_fictitious,name_var))
  }
  
  tmp2 <- NULL
  
  # concatenate data
  tmp <- mbind(tmp1,tmp2)

  return(tmp)
}
  
