#' Read in GDX and calculate electricity generation, used in convGDX2MIF.R for the reporting
#' 
#' Read in electricity generation data from GDX file, information used in convGDX2MIF.R
#' for the reporting
#' 
#' 
#' @param gdx a GDX object as created by readGDX, or the path to a gdx
#' @param output a magpie object containing all needed variables generated by other report*.R functions
#' @return MAgPIE object - contains the Generation variables
#' @author Sebastian Osorio, Renato Rodrigues
#' @seealso \code{\link{convGDX2MIF}}
#' @examples
#' 
#' \dontrun{reportGeneration(gdx)}
#'
#' @importFrom gdx readGDX
#' @importFrom magclass mbind setNames dimSums getSets getSets<- as.magpie
#' @export
#' 
reportGeneration <- function(gdx,output=NULL) {
  
  if(is.null(output)){
    stop("please provide a file containing all needed information")
  }
  
  # read sets
  time <- readGDX(gdx,name="t")
  tehe <- readGDX(gdx,name="tehe")
  teel <- readGDX(gdx,name="teel") #set of electricity generation technologies (non-storage)
  ter <- readGDX(gdx,name="ter") #set of variable renewable electricity generation technologies
  ternofluc <- readGDX(gdx,name="ternofluc") #set of non-variable (non-fluctuating) renewable electricity generation technologies
  tefossil <- readGDX(gdx,name="tefossil") #set of fossil-based electricity generation technologies
  tenr <- readGDX(gdx,name="tenr") #set of non-renewable electricity generation technologies (includes storage)
  tegas <- readGDX(gdx,name="tegas") #set of gas generation technologies
  telig <- readGDX(gdx,name="telig") #set of lignite generation technologies
  tecoal <- readGDX(gdx,name="tecoal") #set of hard coal generation technologies
  tengcc <- readGDX(gdx,name="tengcc") #set of NGCC generation technologies
  tehydro <- readGDX(gdx,name="tehydro") #set of hydropower generation technologies
  tehgen <- readGDX(gdx,name="tehgen")
  tehydro <- readGDX(gdx,name="tehydro")
  tebio <- readGDX(gdx,name="tebio")
  teoil <- readGDX(gdx,name="teoil")
  techp <- readGDX(gdx,name="techp")
  teccs <- readGDX(gdx,name="teccs")
  teothers <- readGDX(gdx,name="teothers")
  tau <- readGDX(gdx,name="tau") #set of time slices
  pety <- readGDX(gdx,name="pety") #set of primary energies
  tegas_el <- intersect(tegas,teel)
  tengcc_el <- intersect(tengcc,teel)
  pe2se <- readGDX(gdx,name="pe2se")
  pe2se <- paste0(pe2se[,1],".",pe2se[,2],".",pe2se[,3])
  
  # read parameters and sets
  p_taulength <- readGDX(gdx,name="p_taulength",field="l",format="first_found")[,,tau] #number of hours/year per tau
  p_tedata <- readGDX(gdx,name="p_tedata",field="l",format="first_found") #parameter per technology
  c_LIMESversion <- readGDX(gdx,name="c_LIMESversion",field="l",format="first_found")
  
  # read variables
  v_seprod <- readGDX(gdx,name="v_seprod",field="l",format="first_found")[,,tau]
  v_storeout <- readGDX(gdx,name="v_storeout",field="l",format="first_found")[,,tau]
  v_storein <- readGDX(gdx,name="v_storein",field="l",format="first_found")[,,tau]
  v_exdemand <- readGDX(gdx,name="v_exdemand",field="l",format="first_found")[,,tau] #demand
  
  #Make sure only the sets -> to reduce the size of the variables
  #v_seprod <- v_seprod[,,pe2se]
  v_seprod <- v_seprod[,,pety]
  p_autocons <- p_tedata[,,"autocons"]

  # create MagPie object of variables with iso3 regions
  v_seprod <- limesMapping(v_seprod)
  v_storeout <- limesMapping(v_storeout)
  v_storein <- limesMapping(v_storein)
  v_exdemand <- limesMapping(v_exdemand)
  p_autocons <- limesMapping(p_autocons)
  
  #Check the version so to choose the electricity-related variables
  if(c_LIMESversion >= 2.28) {
    p_eldemand <- v_exdemand[,,"seel"]
    v_seprod_el <- v_seprod[,,"seel"]
    c_heating <- readGDX(gdx,name="c_heating",field="l",format="first_found")
    if(c_heating == 1) {
      v_seprod_he <- v_seprod[,,"sehe"]
      v_seprod_he <- collapseNames(v_seprod_he)
      #v_seprod_el <- v_seprod[,,"seel"]
    } else {
      #v_seprod_el <- v_seprod
    }
    
  } else {
    p_eldemand <- v_exdemand
    v_seprod_el <- v_seprod
  }
  #Collapse names to avoid some problems
  p_eldemand <- collapseNames(p_eldemand)
  v_seprod_el <- collapseNames(v_seprod_el)
  
  
  #generation per technology ('te') per country
  #and converting from GWh to TWh
  tmp1 <- NULL
  #for (teel2 in teel) {
  #  tmp1 <- mbind(tmp1,setNames(dimSums(v_seprod[,,teel2]*p_taulength/1000,3),paste("Secondary Energy|Electricity|",teel2,"(TWh/yr)")))
  #}
  
  #generation per aggregated technologies per country
  tmp2 <- NULL
  #Conventional
  tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_el[,,c("tnr")]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|Nuclear (TWh/yr)"))
  tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_el[,,intersect(teel,c(telig,tecoal))]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|Coal (TWh/yr)"))
  tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_el[,,c(setdiff(telig,teccs),setdiff(tecoal,teccs))]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|Coal|w/o CCS (TWh/yr)"))
  tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_el[,,intersect(c(telig,tecoal),teccs)]*p_taulength/1000,3),"Secondary Energy|Electricity|Coal|w/ CCS (TWh/yr)"))
  tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_el[,,c(telig)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|Lignite (TWh/yr)"))
  tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_el[,,setdiff(telig,teccs)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|Lignite|w/o CCS (TWh/yr)"))
  tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_el[,,intersect(telig,teccs)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|Lignite|w/ CCS (TWh/yr)"))
  tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_el[,,c(tecoal)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|Hard Coal (TWh/yr)"))
  tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_el[,,c(setdiff(tecoal,teccs))]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|Hard Coal|w/o CCS (TWh/yr)"))
  tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_el[,,intersect(tecoal,teccs)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|Hard Coal|w/ CCS (TWh/yr)"))
  tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_el[,,c(tegas_el)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|Gas (TWh/yr)"))
  tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_el[,,setdiff(tegas_el,teccs)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|Gas|w/o CCS (TWh/yr)"))
  tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_el[,,setdiff(tengcc_el,teccs)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|Gas CC|w/o CCS (TWh/yr)"))
  tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_el[,,c(tengcc_el)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|Gas CC (TWh/yr)"))
  tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_el[,,intersect(tegas_el,teccs)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|Gas|w/ CCS (TWh/yr)"))
  tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_el[,,intersect(tengcc_el,teccs)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|Gas CC|w/ CCS (TWh/yr)"))
  tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_el[,,setdiff(setdiff(tegas_el,tengcc_el),teccs)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|Gas OC|w/o CCS (TWh/yr)"))
  tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_el[,,setdiff(tegas_el,tengcc_el)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|Gas OC (TWh/yr)"))
  tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_el[,,c(teoil)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|Oil (TWh/yr)"))
  tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_el[,,setdiff(teoil,teccs)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|Oil|w/o CCS (TWh/yr)"))
  tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_el[,,c(tebio)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|Biomass (TWh/yr)"))
  tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_el[,,setdiff(tebio,teccs)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|Biomass|w/o CCS (TWh/yr)"))
  tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_el[,,c("waste")]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|Waste (TWh/yr)"))
  tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_el[,,c(tehgen)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|Hydrogen (TWh/yr)"))
  tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_el[,,c(teothers)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|Other (TWh/yr)"))
  tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_el[,,c("hfc")]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|Hydrogen FC (TWh/yr)"))
  tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_el[,,c("hct")]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|Hydrogen OC (TWh/yr)"))
  tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_el[,,c("hcc")]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|Hydrogen CC (TWh/yr)"))
  tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_el[,,c(teothers,"waste",teoil)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|Other Fossil (TWh/yr)"))
  
  #general aggregation
  tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_el[,,c(tefossil)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|Fossil (TWh/yr)"))
  tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_el[,,c(ter)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|Variable renewable (TWh/yr)"))
  tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_el[,,c(ternofluc)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|Non-variable renewable (TWh/yr)"))
  tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_el[,,c(ter,ternofluc)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|Renewable (TWh/yr)"))
  tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_el[,,intersect(teel,tenr)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|Non-renewable (TWh/yr)")) #this does not include storage
  tmp2 <- mbind(tmp2,setNames((dimSums(v_seprod_el[,,c(teel)]*p_taulength,dim=3)+dimSums(v_storeout*p_taulength,dim=3))/1000,"Secondary Energy|Electricity (TWh/yr)"))
  tmp2 <- mbind(tmp2,setNames((dimSums(v_seprod_el[,,c(teel)]*p_taulength,dim=3)+dimSums(v_storeout*p_taulength,dim=3)-dimSums(v_storein*p_taulength,dim=3))/1000,"Secondary Energy||Electricity|w/o losses (TWh/yr)"))

  #Renewable
  tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod[,,c("windon","windoff")]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|Wind (TWh/yr)"))
  tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod[,,c("windon")]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|Wind|Onshore (TWh/yr)"))
  tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod[,,c("windoff")]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|Wind|Offshore (TWh/yr)"))
  tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod[,,c("spv","csp")]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|Solar (TWh/yr)"))
  tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod[,,c("spv")]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|Solar|PV (TWh/yr)"))
  tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod[,,c("csp")]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|Solar|CSP (TWh/yr)"))
  tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod[,,c(tehydro)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|Hydro (TWh/yr)"))
  
  if(c_LIMESversion >= 2.33) {
    tewaste <- readGDX(gdx,name="tewaste") #set of waste generation technologies
    tedh <- readGDX(gdx,name="tedh") #set of District Heating generation technologies
    tedhelec <- readGDX(gdx,name="tedhelec") #set of electric District Heating generation technologies
    if(c_heating == 1) {
      #1) HEAT FROM CHP AND DH
      #1.a) Both
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_he[,,]*p_taulength/1000,dim=3),"Secondary Energy|Heat (TWh/yr)"))
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_he[,,intersect(tehe,c(telig,tecoal))]*p_taulength/1000,dim=3),"Secondary Energy|Heat|Coal (TWh/yr)"))
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_he[,,intersect(tehe,telig)]*p_taulength/1000,dim=3),"Secondary Energy|Heat|Lignite (TWh/yr)"))
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_he[,,intersect(tehe,tecoal)]*p_taulength/1000,dim=3),"Secondary Energy|Heat|Hard Coal (TWh/yr)"))
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_he[,,intersect(tehe,tegas)]*p_taulength/1000,dim=3),"Secondary Energy|Heat|Gas (TWh/yr)"))
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_he[,,intersect(tehe,teoil)]*p_taulength/1000,dim=3),"Secondary Energy|Heat|Oil (TWh/yr)"))
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_he[,,intersect(tehe,tebio)]*p_taulength/1000,dim=3),"Secondary Energy|Heat|Biomass (TWh/yr)"))
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_he[,,intersect(tehe,teothers)]*p_taulength/1000,dim=3),"Secondary Energy|Heat|Other (TWh/yr)"))
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_he[,,intersect(tehe,tewaste)]*p_taulength/1000,dim=3),"Secondary Energy|Heat|Waste (TWh/yr)"))
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_he[,,intersect(tehe,"sol_heat")]*p_taulength/1000,dim=3),"Secondary Energy|Heat|Solar (TWh/yr)"))
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_he[,,intersect(tehe,"geo_heat")]*p_taulength/1000,dim=3),"Secondary Energy|Heat|Geothermal (TWh/yr)"))
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_he[,,intersect(tehe,tedhelec)]*p_taulength/1000,dim=3),"Secondary Energy|Heat|Electricity (TWh/yr)"))
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_he[,,intersect(tehe,tefossil)]*p_taulength/1000,dim=3),"Secondary Energy|Heat|Fossil (TWh/yr)"))
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_he[,,intersect(tehe,c(ter,ternofluc))]*p_taulength/1000,dim=3),"Secondary Energy|Heat|Renewable (TWh/yr)"))
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_he[,,intersect(tehe,tenr)]*p_taulength/1000,dim=3),"Secondary Energy|Heat|Non-renewable (TWh/yr)"))
      
      #1.b) CHP
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_he[,,]*p_taulength/1000,dim=3),"Secondary Energy|Heat|CHP (TWh/yr)"))
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_he[,,intersect(techp,c(telig,tecoal))]*p_taulength/1000,dim=3),"Secondary Energy|Heat|CHP|Coal (TWh/yr)"))
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_he[,,intersect(techp,telig)]*p_taulength/1000,dim=3),"Secondary Energy|Heat|CHP|Lignite (TWh/yr)"))
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_he[,,intersect(techp,tecoal)]*p_taulength/1000,dim=3),"Secondary Energy|Heat|CHP|Hard Coal (TWh/yr)"))
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_he[,,intersect(techp,tegas)]*p_taulength/1000,dim=3),"Secondary Energy|Heat|CHP|Gas (TWh/yr)"))
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_he[,,intersect(techp,tengcc)]*p_taulength/1000,dim=3),"Secondary Energy|Heat|CHP|Gas CC (TWh/yr)"))
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_he[,,intersect(techp,setdiff(tegas,tengcc))]*p_taulength/1000,dim=3),"Secondary Energy|Heat|CHP|Gas OC (TWh/yr)"))
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_he[,,intersect(techp,teoil)]*p_taulength/1000,dim=3),"Secondary Energy|Heat|CHP|Oil (TWh/yr)"))
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_he[,,intersect(techp,tebio)]*p_taulength/1000,dim=3),"Secondary Energy|Heat|CHP|Biomass (TWh/yr)"))
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_he[,,intersect(techp,teothers)]*p_taulength/1000,dim=3),"Secondary Energy|Heat|CHP|Other (TWh/yr)"))      
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_he[,,intersect(techp,tefossil)]*p_taulength/1000,dim=3),"Secondary Energy|Heat|CHP|Fossil (TWh/yr)"))
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_he[,,intersect(techp,c(ter,ternofluc))]*p_taulength/1000,dim=3),"Secondary Energy|Heat|CHP|Renewable (TWh/yr)"))
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_he[,,intersect(techp,tenr)]*p_taulength/1000,dim=3),"Secondary Energy|Heat|CHP|Non-renewable (TWh/yr)"))
      
      #1.c) District Heating
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_he[,,]*p_taulength/1000,dim=3),"Secondary Energy|Heat|District Heating (TWh/yr)"))
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_he[,,intersect(tedh,c(telig,tecoal))]*p_taulength/1000,dim=3),"Secondary Energy|Heat|District Heating|Coal (TWh/yr)"))
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_he[,,intersect(tedh,telig)]*p_taulength/1000,dim=3),"Secondary Energy|Heat|District Heating|Lignite (TWh/yr)"))
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_he[,,intersect(tedh,tecoal)]*p_taulength/1000,dim=3),"Secondary Energy|Heat|District Heating|Hard Coal (TWh/yr)"))
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_he[,,intersect(tedh,tegas)]*p_taulength/1000,dim=3),"Secondary Energy|Heat|District Heating|Gas (TWh/yr)"))
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_he[,,intersect(tedh,teoil)]*p_taulength/1000,dim=3),"Secondary Energy|Heat|District Heating|Oil (TWh/yr)"))
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_he[,,intersect(tedh,tebio)]*p_taulength/1000,dim=3),"Secondary Energy|Heat|District Heating|Biomass (TWh/yr)"))
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_he[,,intersect(tedh,teothers)]*p_taulength/1000,dim=3),"Secondary Energy|Heat|District Heating|Other (TWh/yr)"))
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_he[,,intersect(tedh,tewaste)]*p_taulength/1000,dim=3),"Secondary Energy|Heat|District Heating|Waste (TWh/yr)"))
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_he[,,intersect(tedh,"sol_heat")]*p_taulength/1000,dim=3),"Secondary Energy|Heat|District Heating|Solar (TWh/yr)"))
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_he[,,intersect(tedh,"geo_heat")]*p_taulength/1000,dim=3),"Secondary Energy|Heat|District Heating|Geothermal (TWh/yr)"))
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_he[,,intersect(tedh,tedhelec)]*p_taulength/1000,dim=3),"Secondary Energy|Heat|District Heating|Electricity (TWh/yr)"))
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_he[,,intersect(tedh,"hpump")]*p_taulength/1000,dim=3),"Secondary Energy|Heat|District Heating|Electricity|Heat Pump (TWh/yr)"))
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_he[,,intersect(tedh,"elboil")]*p_taulength/1000,dim=3),"Secondary Energy|Heat|District Heating|Electricity|Electric Boiler (TWh/yr)"))
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_he[,,intersect(tedh,tefossil)]*p_taulength/1000,dim=3),"Secondary Energy|Heat|District Heating|Fossil (TWh/yr)"))
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_he[,,intersect(tedh,c(ter,ternofluc))]*p_taulength/1000,dim=3),"Secondary Energy|Heat|District Heating|Renewable (TWh/yr)"))
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_he[,,intersect(tedh,tenr)]*p_taulength/1000,dim=3),"Secondary Energy|Heat|District Heating|Non-renewable (TWh/yr)"))
      
      
      #2. ELECTRICITY FROM CHP AND ELECTRICITY-ONLY PLANTS
      #2.a) CHP
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_el[,,c(techp)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|CHP (TWh/yr)"))
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_el[,,intersect(techp,c(telig,tecoal))]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|CHP|Coal (TWh/yr)"))
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_el[,,intersect(techp,telig)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|CHP|Lignite (TWh/yr)"))
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_el[,,intersect(techp,tecoal)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|CHP|Hard Coal (TWh/yr)"))
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_el[,,intersect(techp,tegas)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|CHP|Gas (TWh/yr)"))
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_el[,,intersect(techp,tengcc)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|CHP|Gas CC (TWh/yr)"))
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_el[,,intersect(techp,setdiff(tegas,tengcc))]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|CHP|Gas OC (TWh/yr)"))
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_el[,,intersect(techp,teoil)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|CHP|Oil (TWh/yr)"))
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_el[,,intersect(techp,tebio)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|CHP|Biomass (TWh/yr)"))
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_el[,,intersect(techp,teothers)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|CHP|Other (TWh/yr)"))
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_el[,,intersect(techp,tefossil)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|CHP|Fossil (TWh/yr)"))
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_el[,,intersect(techp,c(ter,ternofluc))]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|CHP|Renewable (TWh/yr)"))
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_el[,,intersect(techp,tenr)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|CHP|Non-renewable (TWh/yr)")) 
      
      #2.b) Electricity-only
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_el[,,c(setdiff(teel,techp))]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|Electricity-only (TWh/yr)"))
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_el[,,intersect(setdiff(teel,techp),c(telig,tecoal))]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|Electricity-only|Coal (TWh/yr)"))
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_el[,,intersect(setdiff(teel,techp),telig)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|Electricity-only|Lignite (TWh/yr)"))
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_el[,,intersect(setdiff(teel,techp),tecoal)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|Electricity-only|Hard Coal (TWh/yr)"))
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_el[,,intersect(setdiff(teel,techp),tegas)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|Electricity-only|Gas (TWh/yr)"))
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_el[,,intersect(setdiff(teel,techp),tengcc)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|Electricity-only|Gas CC (TWh/yr)"))
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_el[,,intersect(setdiff(teel,techp),setdiff(tegas,tengcc))]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|Electricity-only|Gas OC (TWh/yr)"))
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_el[,,intersect(setdiff(teel,techp),teoil)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|Electricity-only|Oil (TWh/yr)"))
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_el[,,intersect(setdiff(teel,techp),tebio)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|Electricity-only|Biomass (TWh/yr)"))
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_el[,,intersect(setdiff(teel,techp),teothers)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|Electricity-only|Other (TWh/yr)"))
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_el[,,intersect(setdiff(teel,techp),tewaste)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|Electricity-only|Waste (TWh/yr)"))
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_el[,,intersect(setdiff(teel,techp),tefossil)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|Electricity-only|Fossil (TWh/yr)"))
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_el[,,intersect(setdiff(teel,techp),c(ter,ternofluc))]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|Electricity-only|Renewable (TWh/yr)"))
      tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod_el[,,intersect(setdiff(teel,techp),tenr)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|Electricity-only|Non-renewable (TWh/yr)")) 
      
      
      #3) ELECTRICITY AND HEAT -> Does not make much sense
      #tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod[,,c("tnr")]*p_taulength/1000,dim=3),"Secondary Energy|Electricity and Heat|Nuclear (TWh/yr)"))
      #tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod[,,c(telig,tecoal)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity and Heat|Coal (TWh/yr)"))
      #tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod[,,c(setdiff(telig,teccs),setdiff(tecoal,teccs))]*p_taulength/1000,dim=3),"Secondary Energy|Electricity and Heat|Coal|w/o CCS (TWh/yr)"))
      #tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod[,,intersect(c(telig,tecoal),teccs)]*p_taulength/1000,3),"Secondary Energy|Electricity and Heat|Coal|w/ CCS (TWh/yr)"))
      #tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod[,,c(telig)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity and Heat|Lignite (TWh/yr)"))
      #tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod[,,setdiff(telig,teccs)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity and Heat|Lignite|w/o CCS (TWh/yr)"))
      #tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod[,,intersect(telig,teccs)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity and Heat|Lignite|w/ CCS (TWh/yr)"))
      #tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod[,,c(tecoal)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity and Heat|Hard Coal (TWh/yr)"))
      #tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod[,,c(setdiff(tecoal,teccs))]*p_taulength/1000,dim=3),"Secondary Energy|Electricity and Heat|Hard Coal|w/o CCS (TWh/yr)"))
      #tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod[,,intersect(tecoal,teccs)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity and Heat|Hard Coal|w/ CCS (TWh/yr)"))
      #tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod[,,c(tegas)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity and Heat|Gas (TWh/yr)"))
      #tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod[,,setdiff(tegas,teccs)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity and Heat|Gas|w/o CCS (TWh/yr)"))
      #tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod[,,setdiff(tengcc,teccs)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity and Heat|Gas CC|w/o CCS (TWh/yr)"))
      #tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod[,,c(tengcc)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity and Heat|Gas CC (TWh/yr)"))
      #tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod[,,intersect(tegas,teccs)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity and Heat|Gas|w/ CCS (TWh/yr)"))
      #tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod[,,intersect(tengcc,teccs)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity and Heat|Gas CC|w/ CCS (TWh/yr)"))
      #tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod[,,setdiff(setdiff(tegas,tengcc),teccs)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity and Heat|Gas OC|w/o CCS (TWh/yr)"))
      #tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod[,,setdiff(tegas,tengcc)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity and Heat|Gas OC (TWh/yr)"))
      #tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod[,,c(teoil)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity and Heat|Oil (TWh/yr)"))
      #tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod[,,setdiff(teoil,teccs)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity and Heat|Oil|w/o CCS (TWh/yr)"))
      #tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod[,,c(tebio)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity and Heat|Biomass (TWh/yr)"))
      #tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod[,,setdiff(tebio,teccs)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity and Heat|Biomass|w/o CCS (TWh/yr)"))
      #tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod[,,c("waste")]*p_taulength/1000,dim=3),"Secondary Energy|Electricity and Heat|Waste (TWh/yr)"))
      #tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod[,,c(tehgen)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity and Heat|Hydrogen (TWh/yr)"))
      #tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod[,,c(teothers)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity and Heat|Other (TWh/yr)"))
      #tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod[,,c("hfc")]*p_taulength/1000,dim=3),"Secondary Energy|Electricity and Heat|Hydrogen FC (TWh/yr)"))
      #tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod[,,c("hct")]*p_taulength/1000,dim=3),"Secondary Energy|Electricity and Heat|Hydrogen OC (TWh/yr)"))
      #tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod[,,c("hcc")]*p_taulength/1000,dim=3),"Secondary Energy|Electricity and Heat|Hydrogen CC (TWh/yr)"))
      #tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod[,,c(teothers,"waste",teoil)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity and Heat|Other Fossil (TWh/yr)"))
      #
      ##general aggregation
      #tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod[,,c(tefossil)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity and Heat|Fossil (TWh/yr)"))
      #tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod[,,c(ter,ternofluc)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity and Heat|Renewable (TWh/yr)"))
      #tmp2 <- mbind(tmp2,setNames(dimSums(v_seprod[,,intersect(union(teel,tehe),tenr)]*p_taulength/1000,dim=3),"Secondary Energy|Electricity and Heat|Non-renewable (TWh/yr)")) #this does not include storage
      #tmp2 <- mbind(tmp2,setNames((dimSums(v_seprod[,,union(teel,tehe)]*p_taulength,dim=3)+dimSums(v_storeout*p_taulength,dim=3))/1000,"Secondary Energy|Electricity and Heat (TWh/yr)"))
      
    }
  }
  
  # add global values
  tmp3 <- mbind(tmp1,tmp2)
  
  #Storage
  tmp4 <- NULL
  tmp4 <- mbind(tmp4,setNames(dimSums(v_storeout*p_taulength/1000,dim=3),"Secondary Energy|Electricity|Storage (TWh/yr)"))
  tmp4 <- mbind(tmp4,setNames(dimSums(v_storeout[,,"psp"]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|Storage|Pump Hydro (TWh/yr)"))
  tmp4 <- mbind(tmp4,setNames(dimSums(v_storeout[,,"batteries"]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|Storage|Stat Batteries (TWh/yr)"))
  tmp4 <- mbind(tmp4,setNames(dimSums(v_storeout[,,"helec"]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|Storage|Hydrogen electrolysis (TWh/yr)"))
  tmp4 <- mbind(tmp4,setNames(dimSums(v_storein*p_taulength/1000,dim=3),"Secondary Energy|Electricity|Storage Consumption (TWh/yr)"))
  tmp4 <- mbind(tmp4,setNames(dimSums(v_storein[,,"psp"]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|Storage Consumption|Pump Hydro (TWh/yr)"))
  tmp4 <- mbind(tmp4,setNames(dimSums(v_storein[,,"batteries"]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|Storage Consumption|Stat Batteries (TWh/yr)"))
  tmp4 <- mbind(tmp4,setNames(dimSums(v_storein[,,"helec"]*p_taulength/1000,dim=3),"Secondary Energy|Electricity|Storage Consumption|Hydrogen electrolysis (TWh/yr)"))
  tmp4 <- mbind(tmp4,setNames(dimSums(collapseNames(v_storein-v_storeout)*collapseNames(p_taulength)/1000,dim=3),"Secondary Energy|Electricity|Storage Losses (TWh/yr)"))
  
  tmp5 <- mbind(tmp3,tmp4)
  
  #Gross demand
  tmp6 <- NULL
  #Need to create a variable with t,regi,te for gross production (v_seprod has these indexes)
  p_grossprod <- new.magpie(cells_and_regions = getRegions(v_seprod_el), years = getYears(v_seprod_el), names = getNames(v_seprod_el[,,teel]),
                                       fill = 0, sort = FALSE, sets = NULL, unit = "unknown")
  
  #p_grossprod[,,] <- v_seprod_el[,,]*(1+p_autocons[,,teel])
  #
  #for (teel2 in teel) {
  #  p_grossprod[,,teel2] <- v_seprod_el[,,teel2]*(1+p_autocons[,,teel2])
  #  #tmp6 <- mbind(tmp6,setNames(dimSums(p_grossprod[,,teel2]*p_taulength/1000,dim=3),paste("Gross Production|Electricity|",teel2,"(TWh/yr)")))
  #} 
  #
  for (regi2 in getRegions(v_seprod_el)) {
    p_grossprod[regi2,,] <- collapseNames(v_seprod_el[regi2,,teel]*(1+p_autocons[regi2,,teel]))
    #tmp6 <- mbind(tmp6,setNames(dimSums(p_grossprod[,,teel2]*p_taulength/1000,dim=3),paste("Gross Production|Electricity|",teel2,"(TWh/yr)")))
  }
  tmp6 <- mbind(tmp6,setNames(dimSums(p_grossprod[,,intersect(teel,c(telig))]*p_taulength/1000,dim=3),"Gross Production|Electricity|Lignite (TWh/yr)"))
  tmp6 <- mbind(tmp6,setNames(dimSums(p_grossprod[,,intersect(teel,c(tecoal))]*p_taulength/1000,dim=3),"Gross Production|Electricity|Coal (TWh/yr)"))
  tmp6 <- mbind(tmp6,setNames(dimSums(p_grossprod[,,intersect(teel,c(tegas))]*p_taulength/1000,dim=3),"Gross Production|Electricity|Gas (TWh/yr)"))
  tmp6 <- mbind(tmp6,setNames(dimSums(p_grossprod[,,intersect(teel,c(tefossil))]*p_taulength/1000,dim=3),"Gross Production|Electricity|Fossil (TWh/yr)"))
  tmp6 <- mbind(tmp6,setNames(dimSums(p_grossprod[,,intersect(teel,c("tnr"))]*p_taulength/1000,dim=3),"Gross Production|Electricity|Nuclear (TWh/yr)"))
  
  #Net imports
  p_netimpots <- new.magpie(cells_and_regions = getRegions(p_eldemand), years = getYears(p_eldemand), names = tau,
                                         fill = 0, sort = FALSE, sets = NULL, unit = "unknown")
  p_netimpots <- dimSums(p_eldemand*p_taulength/1000,dim=3) - dimSums(v_seprod_el*p_taulength/1000,dim=3) + tmp4[,,"Secondary Energy|Electricity|Storage Losses (TWh/yr)"]
  
  #Gross demand (gross electricity production + net imports), following official german statistics procedure
  p_grossdem <- dimSums(p_grossprod*p_taulength/1000,dim=3) + p_netimpots
  tmp6 <- mbind(tmp6,setNames(p_grossdem,"Secondary Energy|Electricity|Gross Demand (TWh/yr)"))
  
  #Shares
  tmp7 <- NULL
  tmp7 <- mbind(tmp7,setNames(dimSums(p_grossprod[,,intersect(teel,c(ter,ternofluc))]*p_taulength/1000,dim=3)/p_grossdem,"Secondary Energy|Electricity|Share of renewables in gross demand (--)"))
  
  tmp8 <- mbind(tmp6,tmp7)
  
  # add global values
  tmp9 <- mbind(tmp5,tmp8)
  
  #Load primary energy values, add renewable and calculate total -> Not very useful
  # read variables that have been already calculated in other functions (emissions and trade costs)
  #o_pedem <- output[,,"Primary Energy|Electricity [exhaustible resources] (TWh/yr)"]
  #For these technologies, primary energy variable does not exist in LIMES, so it is calculated based on their generation
  tmp10 <- NULL
  #tmp10 <- mbind(tmp10,setNames(dimSums(v_seprod[,,c("spv","csp")]*p_taulength/1000,3),"Primary Energy|Electricity|Solar (TWh/yr)"))
  #tmp10 <- mbind(tmp10,setNames(dimSums(v_seprod[,,c("windon","windoff")]*p_taulength/1000,3),"Primary Energy|Electricity|Wind (TWh/yr)"))
  #tmp10 <- mbind(tmp10,setNames(dimSums(v_seprod[,,c(tehydro)]*p_taulength/1000,3),"Primary Energy|Electricity|Hydro (TWh/yr)"))
  
  #combining all the primary sources
  #tmp10 <- mbind(tmp10,setNames(o_pedem+dimSums(v_seprod[,,c(ter,tehydro)]*p_taulength/1000,3),"Primary Energy|Electricity (TWh/yr)"))
  
  tmp <- mbind(tmp9,tmp10)

  return(tmp)
}
  
